apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-mcp-supergateway
  labels:
    {{- include "agentstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: managed-mcp-supergateway
automountServiceAccountToken: true
