# check

["supergateway:check"]
depends = ["supergateway:check:*"]

["supergateway:check:hadolint"]
extends = "docker:check:hadolint"
dir = "{{config_root}}/apps/supergateway"

# build

["supergateway:build"]
dir = "{{config_root}}/apps/supergateway"
run = "docker build -f Dockerfile -t ghcr.io/i-am-bee/agentstack/supergateway:latest --load ."
sources = ["*"]
outputs = { auto = true }
