# check

["agentstack-sdk-ts:check"]
depends = ["agentstack-sdk-ts:check:*"]

["agentstack-sdk-ts:check:prettier"]
extends = "node:check:prettier"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"

["agentstack-sdk-ts:check:eslint"]
extends = "node:check:eslint"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"

["agentstack-sdk-ts:check:tsc"]
extends = "node:check:tsc"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"
run = "pnpm tsc --noEmit -p tsconfig.check.json"

# fix

["agentstack-sdk-ts:fix"]
depends = ["agentstack-sdk-ts:fix:*"]

["agentstack-sdk-ts:fix:prettier"]
extends = "node:fix:prettier"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"

["agentstack-sdk-ts:fix:lint"]
extends = "node:fix:eslint"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"

# build

["agentstack-sdk-ts:build"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/agentstack-sdk-ts"
run = "pnpm build"
sources = ["src/**/*", "package.json", "tsconfig.json"]
outputs = { auto = true }
