apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge
  labels:
    app: forge
    {{- include "beeai-platform.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forge
      {{- include "beeai-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: forge
        {{- include "beeai-platform.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/forge/config.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.forge.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway
          {{- with .Values.forge.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.forge.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.forge.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.forge.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.forge.config.PORT }}
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: forge-secret
            - configMapRef:
                name: forge-config
          {{- with .Values.forge.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.forge.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.forge.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
